import sources from "../data/sources.json";
import goalRules from "../data/goalRules.json";
import partRules from "../data/partRules.json";
import symptomRules from "../data/symptomRules.json";
import feedbackRules from "../data/feedbackRules.json";
import dependencyRules from "../data/dependencyRules.json";
import carCatalogData from "../data/carCatalog.json";
import type {
  CarCatalogEntry,
  DependencyRule,
  FeedbackRule,
  GoalRule,
  PartRule,
  RuleBundle,
  SourceRecord,
  SymptomRule,
} from "../types/rules";

export const carCatalog: CarCatalogEntry[] = (carCatalogData as { cars: CarCatalogEntry[] }).cars;

export const rules: RuleBundle = {
  sources: sources as SourceRecord[],
  goalRules: goalRules as GoalRule[],
  partRules: partRules as PartRule[],
  symptomRules: symptomRules as SymptomRule[],
  feedbackRules: feedbackRules as FeedbackRule[],
  dependencyRules: dependencyRules as DependencyRule[],
};

export const labelMap: Record<string, string> = {
  road: "公路",
  street: "街头",
  touge: "峠道",
  road_racing: "公路竞速赛",
  dirt_racing: "泥地竞速赛",
  cross_country: "越野竞速赛",
  street_racing: "街头竞速赛",
  drag_racing: "直线加速赛",
  time_attack: "计时赛",
  speed_traps: "测速照相",
  speed_zones: "测速区间",
  danger_signs: "危险标志",
  drift_zones: "漂移区域",
  trailblazers: "拓荒者",
  speed: "速度优先",
  balanced: "均衡",
  handling: "操控优先",
  A: "A级",
  S1: "S1级",
  S2: "S2级",
  R: "R级",
  B: "B级",
  C: "C级",
  D: "D级",
  RWD: "后驱",
  AWD: "全驱",
  FWD: "前驱",
  tire_compound: "轮胎配方",
  tire_width: "轮胎宽度",
  rim: "轮圈",
  suspension: "弹簧与阻尼",
  antiroll_bars: "防倾杆",
  brakes: "刹车",
  weight_reduction: "减重",
  chassis_reinforcement: "车身强化",
  differential: "差速器",
  transmission: "变速箱",
  aero_front: "前保险杠/前空力",
  aero_rear: "尾翼/后空力",
  engine_upgrades: "引擎升级",
  driveline: "传动轴",
  flywheel: "飞轮",
  clutch: "离合器",
  widebody: "宽体套件",
  rally_springs: "拉力悬挂",
  offroad_springs: "越野悬挂",
  rally_tires: "拉力胎",
  offroad_tires: "越野胎",
  drift_tires: "漂移胎",
  slick_tires: "光头胎",
  exhaust: "排气",
  intake: "进气",
  intake_manifold: "进气歧管",
  ignition: "点火系统",
  fuel_system: "燃油系统",
  camshaft: "凸轮轴",
  pistons: "活塞与压缩",
  valves: "气门",
  displacement: "排量",
  oil_cooling: "机油与冷却",
  hood: "引擎盖",
  side_skirts: "侧裙",
  drivetrain_conversion: "驱动形式转换",
  engine_swap: "引擎互换",
  aspiration: "进气形式",
  tunable_brakes: "可调刹车",
  tunable_suspension: "可调悬挂",
  tunable_antiroll_bars: "可调防倾杆",
  tunable_differential: "可调差速器",
  tunable_front_aero: "可调前下压力",
  tunable_rear_aero: "可调后下压力",
  adjustable_gearing: "可调齿比",
  entry_understeer: "入弯推头",
  mid_corner_understeer: "弯中推头",
  exit_power_understeer: "出弯给油推头",
  exit_power_oversteer: "出弯甩尾",
  braking_instability: "刹车时车尾不稳",
  high_speed_instability: "高速发飘",
  low_top_speed: "直线太慢",
  launch_wheelspin: "起步打滑",
  curb_bouncing: "压路肩弹跳",
  sluggish_response: "转向响应迟钝",
  long_braking_distance: "刹车距离长",
  corner_exit_wheelspin: "出弯打滑",
  greatly_improved: "明显改善",
  slightly_improved: "稍微改善",
  no_change: "无变化",
  worse: "变差",
  fh6_game_data: "FH6 游戏文件提取数据",
  fh6_tuning_guide: "FH6 调校指南",
  official: "官方数据",
  authority_guide: "权威指南",
  high: "高",
  medium: "中",
  low: "低",
  goal_wizard: "目标向导",
};

export const categoryLabels: Record<string, string> = {
  tires: "轮胎与轮圈",
  platform: "平台与操控",
  engine: "引擎",
  aero: "空气动力学",
  drivetrain: "传动系统",
  conversion: "转换",
};

export const categoryOrder: string[] = ["tires", "platform", "drivetrain", "aero", "engine", "conversion"];

export function labelOf(value: string): string {
  return labelMap[value] ?? value;
}
