import sources from "../data/sources.json";
import goalRules from "../data/goalRules.json";
import partRules from "../data/partRules.json";
import symptomRules from "../data/symptomRules.json";
import feedbackRules from "../data/feedbackRules.json";
import dependencyRules from "../data/dependencyRules.json";
import sampleBuilds from "../data/sampleBuilds.json";
import sampleCars from "../data/sampleCars.json";
import type {
  DependencyRule,
  FeedbackRule,
  GoalRule,
  PartRule,
  RuleBundle,
  SourceRecord,
  SymptomRule,
} from "../types/rules";

export const rules: RuleBundle = {
  sources: sources as SourceRecord[],
  goalRules: goalRules as GoalRule[],
  partRules: partRules as PartRule[],
  symptomRules: symptomRules as SymptomRule[],
  feedbackRules: feedbackRules as FeedbackRule[],
  dependencyRules: dependencyRules as DependencyRule[],
};

export const starterSamples = {
  sampleBuilds,
  sampleCars,
};

export const labelMap: Record<string, string> = {
  road: "公路",
  street: "街头",
  touge: "山路 Touge",
  stable: "稳定优先",
  balanced: "均衡",
  rotation: "更愿意转向",
  tire_compound: "轮胎胶料",
  tire_width: "胎宽",
  widebody_kit: "宽体套件",
  brakes: "刹车",
  suspension: "悬挂",
  antiroll_bars: "防倾杆",
  transmission: "变速箱",
  differential: "差速器",
  aero_front: "前空力",
  aero_rear: "后空力",
  aero_balance: "前后空力平衡",
  weight_reduction: "减重",
  power: "发动机动力升级",
  braking_control: "刹车更稳定",
  cornering_grip: "弯中抓地更好",
  exit_traction: "出弯牵引更好",
  unlock_tuning: "解锁可调项目",
  balance_control: "更容易调整前后平衡",
  gear_control: "更容易匹配齿比",
  top_speed: "直线尾速",
  acceleration: "加速",
  high_speed_stability: "高速稳定性",
  direction_change: "变向响应",
  high_speed_grip: "高速抓地",
  corner_exit_balance: "出弯平衡",
  pi_budget: "占用 PI 空间",
  possible_top_speed_loss: "可能牺牲直线速度",
  needs_testing: "需要实测确认",
  wheelspin: "更容易打滑",
  understeer: "可能推头",
  drag: "风阻增加",
  increase_mechanical_grip: "提高机械抓地",
  improve_braking: "改善刹车",
  improve_corner_speed: "提高弯速",
  improve_traction: "改善牵引",
  improve_braking_stability: "提升刹车稳定性",
  may_unlock_wider_tires: "可能解锁更宽胎",
  can_change_vehicle_weight_and_track: "可能改变重量和轮距",
  improve_braking_control: "改善制动控制",
  unlock_brake_bias: "解锁刹车平衡调校",
  unlock_brake_pressure: "解锁刹车压力调校",
  unlock_ride_height: "解锁车高调校",
  unlock_spring_damper_tuning: "解锁弹簧和阻尼调校",
  improve_platform_control: "改善车身姿态控制",
  change_front_rear_roll_balance: "改变前后侧倾平衡",
  adjust_understeer_oversteer: "调整推头/甩尾倾向",
  unlock_gear_ratio_tuning: "解锁齿比调校",
  improve_acceleration_band: "改善加速区间",
  reduce_unwanted_shifts: "减少不必要换挡",
  unlocks_key_handling_adjustment: "解锁关键操控调校",
  improve_corner_exit_balance: "改善出弯平衡",
  change_understeer_oversteer_behavior: "改变推头/甩尾倾向",
  improve_front_high_speed_grip: "改善高速前轴抓地",
  help_mid_high_speed_turn_in: "帮助中高速入弯",
  improve_rear_high_speed_stability: "改善高速尾部稳定",
  help_confidence_in_fast_corners: "提升高速弯信心",
  improve_acceleration: "改善加速",
  improve_direction_change: "改善变向响应",
  improve_straight_speed: "提升直线速度",
  pi_cost_can_be_high: "PI 成本可能较高",
  may_reduce_top_speed_or_acceleration_budget: "可能挤占极速或加速空间",
  may_reduce_top_speed: "可能降低直线速度",
  may_increase_weight_feel: "可能让车感更沉",
  pi_effect_can_vary: "PI 变化需要进游戏确认",
  may_add_weight: "可能增加重量",
  not_available_on_every_car: "不是每台车都能安装",
  pi_cost_without_lap_time_gain_if_driver_does_not_need_it: "如果你不需要更强刹车，可能花了 PI 却不涨圈速",
  wrong_values_can_cause_bouncing_or_snap_behavior: "调错可能导致弹跳或突然失控",
  too_extreme_values_can_reduce_grip_or_make_car_nervous: "极端数值可能降低抓地或让车变敏感",
  wrong_final_drive_can_hurt_top_speed_or_launch: "终传不合适会伤害尾速或起步",
  wrong_values_can_make_car_worse: "调错会让车更难开",
  requires_feedback_loop_testing: "需要配合测试反馈",
  less_effective_for_low_speed_mechanical_grip_issues: "对低速机械抓地问题帮助有限",
  may_increase_understeer: "可能加重推头",
  can_make_weight_transfer_faster: "可能让重心转移更快、更敏感",
  can_create_wheelspin: "可能带来打滑",
  can_push_pi_over_limit: "可能把 PI 推超标",
  can_hide_handling_problems: "可能掩盖真正的操控问题",
  corner_exit_wheelspin: "出弯打滑",
  instability_under_braking: "刹车不稳",
  high_power_builds: "高动力构建",
  traction_issues: "牵引不足",
  wide_tire_builds: "需要更宽胎的构建",
  late_braking: "重刹/晚刹",
  mid_corner_balance: "弯中平衡",
  high_speed_turn_in_weakness: "高速入弯前端弱",
  rear_instability_high_speed: "高速尾部不稳",
  braking_instability_at_speed: "高速刹车不稳",
  sluggish_handling: "转向响应迟钝",
  braking_distance: "刹车距离长",
  touge_direction_changes: "山路连续变向",
  stability_issues: "稳定性问题",
  pi_budget_is_tight_and_current_tire_is_already_sufficient: "PI 很紧，而且当前轮胎已经够用",
  car_already_feels_sluggish_on_long_straights: "车在长直线已经偏慢",
  pi_budget_is_tight_and_core_handling_parts_are_missing: "PI 很紧，核心操控件还没补齐",
  only_reason_is_visual: "只是为了外观",
  pi_budget_is_tight_without_testing: "PI 很紧但还没测试收益",
  driver_rarely_locks_or_overheats_braking_phase: "你很少在刹车阶段锁死或失控",
  user_will_not_tune_or_test_adjustments: "不打算做后续调校和测试",
  tire_or_alignment_problem_is_unidentified: "轮胎或定位问题还没排除",
  stock_gearing_already_matches_track: "原厂齿比已经适合这条路线",
  user_has_not_identified_vehicle_problem_yet: "还没有明确车辆问题",
  main_problem_is_low_speed_exit_traction: "主要问题是低速出弯牵引",
  main_problem_is_top_speed_on_long_highways: "主要目标是长直线极速",
  car_already_understeers: "车辆已经明显推头",
  car_is_built_for_top_speed: "这台车主要为极速构建",
  pi_over_limit_and_core_grip_parts_missing: "PI 已超标且核心抓地件还没补齐",
  car_already_has_exit_oversteer: "车辆已经出弯甩尾",
  car_cannot_brake_or_turn_consistently: "车辆还不能稳定刹车或转向",
  blind_power_upgrade: "盲目堆动力",
  sacrificing_brakes_for_power: "为了动力牺牲刹车",
  max_rear_aero_without_front_balance: "只拉满后空力不管前端",
  remove_forced_induction_first: "优先拆高副作用增压/动力件",
  downgrade_engine_power_parts: "下调动力件",
  downgrade_weight_reduction: "必要时下调减重等级",
  downgrade_front_tire_width: "最后再考虑退前胎宽",
  avoid_removing_core_handling_parts_first: "不要先拆核心操控件",
  all_power_no_control: "只堆动力不补控制",
  removing_brakes_before_power: "先拆刹车再留动力",
  reduce_nonessential_power_parts: "减少非必要动力件",
  check_aero_balance_before_removing_brakes_or_diff: "拆刹车/差速前先查空力平衡",
  downgrade_weight_reduction_if_handling_parts_are_required: "保留核心操控件后再权衡减重",
};

export function labelOf(value: string): string {
  return labelMap[value] ?? value.replace(/_/g, " ");
}
